name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repository...
        uses: actions/checkout@v2

      - name: Setting up Node.js environment...
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x

      - name: Loading cached node modules...
        uses: actions/cache@v1.2.0
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Installing dependencies...
        run: yarn install --frozen-lockfile

      - name: Linting...
        run: yarn lint

      - name: Testing...
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 92033c3ebd48d5d2d35e510c3f63b4caa0d1ee7d517e47c6be71cbd73eabf4c1
        with:
          coverageCommand: yarn test --ci --coverage --maxWorkers=2

      - name: Checking for vulnerabilities...
        uses: snyk/actions@0.1.1
